apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-new
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: test
    name: test-pvc-1
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/neone-space-00001/zones/us-central1-a/disks/pvc-796194b7-9361-4a79-81d0-e4cbfe9215e7
    fsType: ext4