apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-1
  labels:
    demo: test-pvc-1
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  volumeName: test-pv